---
- name: Apache serveur web
  hosts: 192.168.232.135
  become: yes

  tasks:
    - name: Apache last ver
      apt:
        name: apache2
        state: latest

    - name: Start apache
      service:
        name: apache2
        state: started
        enabled: yes